// This file is auto-generated by @hey-api/openapi-ts

export { getApiWalkerHealth, type Options, postApiWalkerWalk } from "./sdk.gen";
export type {
  ClientOptions,
  GetApiWalkerHealthData,
  GetApiWalkerHealthResponse,
  GetApiWalkerHealthResponses,
  PostApiWalkerWalkData,
  PostApiWalkerWalkResponse,
  PostApiWalkerWalkResponses,
} from "./types.gen";
