// This file is auto-generated by @hey-api/openapi-ts

export { getApiWalkerHealth, type Options } from "./sdk.gen";
export type {
  ClientOptions,
  GetApiWalkerHealthData,
  GetApiWalkerHealthResponse,
  GetApiWalkerHealthResponses,
} from "./types.gen";
