// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};

export type GetApiWalkerHealthData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/walker/health";
};

export type GetApiWalkerHealthResponses = {
  /**
   * 200 OK
   */
  200: string;
};

export type GetApiWalkerHealthResponse =
  GetApiWalkerHealthResponses[keyof GetApiWalkerHealthResponses];
